export const env = {
  TESTING_MODE: process.env.TESTING_MODE ?? "true",
  //FRONTEND VARIABLES
  NFT_CONTRACT_ADDRESS_TESTNET:
    process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS_TESTNET ??
    "0x72127343c6950ADbf2Ccd4B709f94F7e74f9DD70",
  TOKENID_TESTNET: process.env.NEXT_PUBLIC_TOKENID_TESTNET ?? "4",
  NFT_CONTRACT_ADDRESS_MAINNET:
    process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS_MAINNET ??
    "0x72127343c6950ADbf2Ccd4B709f94F7e74f9DD70",
  TOKENID_MAINNET: process.env.NEXT_PUBLIC_TOKENID_MAINNET ?? "8",
  FRONTEND_BASE_URL_DEV:
    process.env.FRONTEND_BASE_URL_DEV ?? "http://localhost:3000/",
  FRONTEND_BASE_URL_PROD:
    process.env.FRONTEND_BASE_URL_PROD ??
    "https://lit-unity-serverless-oconnor.vercel.app/",

  LIT_CHAIN_TESTNET: process.env.LIT_CHAIN_TESTNET ?? "mumbai",
  LIT_CHAIN_MAINNET: process.env.LIT_CHAIN_MAINNET ?? "mumbai",

  //SERVER VARIABLES
  UNITY_APP_NAME: process.env.NEXT_PUBLIC_UNITY_APP_NAME ?? "tetrisdemoone",
  UNITY_BUILD_PATH: process.env.UNITY_BUILD_PATH ?? "/unitybuild/test/",
};
